### ISSUE TITLE
Mac OS: Editor background color is uneven

### ISSUE THREAD

**Issue by abclive** [edsulaiman/jetbrains-rider-dark-theme#1]
Hi,

First of all, I just wanted to thank you for this great theme, I use it on all of my vscode setups and it's been great. I've recently started working on Mac however and I noticed a problem with the code editor background. Some parts of the background use a different gray than others.

I don't have much experience in theme making but this is what I figured out. It looks like there's a semi-opaque zone going above the editor's background but I wasn't able to find it in the inspector. However I noticed that if I comment out the .monaco-editor background then it becomes one color again.

Here's a screenshot of the problem:
![Screen Shot 2022-07-24 at 3 20 34 PM](https://user-images.githubusercontent.com/5982073/180662792-abf02e58-89a4-4e77-8632-876c050e14c6.png)

Here's what it looks like with the monaco-editor background commented out:
![Screen Shot 2022-07-24 at 3 20 46 PM](https://user-images.githubusercontent.com/5982073/180662806-1faed77b-eaa3-421d-b5ab-2eb37b887498.png)

Let me know if you need more details or if I can help in any way and thanks again!

**Comment by edsulaiman** [comment]
Thank you for reporting this issue. But, I don't see this issue on my windows or macos. I will investigate this issue further

**Comment by abclive** [comment]
Happy to report that as of vscode 1.70 this is no longer an issue!
