### ISSUE TITLE
Request to add Rider Melon Dark

### ISSUE THREAD

**Issue by tzh-just** [edsulaiman/jetbrains-rider-dark-theme#2]
I'll appreciate it very much if you could add this theme

**Comment by thomasbergersen** [comment]
The same requirements

**Comment by tzh-just** [comment]
> The same requirements

I realized the melon theme based on this repo. If you are willing to install it manually by yourself, you can find the melon theme in branch `melon` from my fork.

**Comment by edsulaiman** [comment]
> > The same requirements
> 
> I realized the melon theme based on this repo. If you are willing to install it manually by yourself, you can find the melon theme in branch `melon` from my fork.

I will mention your theme on README.md if you release it

**Comment by tzh-just** [comment]
Of course, it's my pleasure, if my realization is qualified
