### ISSUE TITLE
Make variables color more white

### ISSUE THREAD

**Issue by se-omarayman** [edsulaiman/jetbrains-rider-dark-theme#3]
Hi, so the variable colors is a bit dim, unlike rider, I attached a photo comparison between the two.

from vscode
![image](https://user-images.githubusercontent.com/56203198/193613550-f5b84284-1034-4357-85e7-33791cfe9aaa.png)

from rider
![image](https://user-images.githubusercontent.com/56203198/193613762-7cb5f673-708b-4c4d-bbb5-bf0f42dc1af9.png)

Thanks

**Comment by enkelmedia** [comment]
I'll up vote this one as well, just compared on latest Rider 2023.2 with "Rider Night" theme and the "white" color should be changed from `#a5a5aa` to `#bdbdbd`.

@edsulaiman would you care to update or I can make a PR if you could like to include it?
