### ISSUE TITLE
The sub-menus don't follow theme color palette

### ISSUE THREAD

**Issue by DiogoBnfr** [edsulaiman/jetbrains-rider-dark-theme#8]
VS Code:
![image](https://github.com/edsulaiman/jetbrains-rider-dark-theme/assets/111098897/d8a10542-c512-4fde-82a2-107672f9276c)
Rider:
![image](https://github.com/edsulaiman/jetbrains-rider-dark-theme/assets/111098897/86587227-da13-45dd-9ba3-6fd89b240272)

**Comment by edsulaiman** [comment]
close a4ee7db
